spring:
  application:
    name: coin-desk api
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    username: user
    password: pwd
    driverClassName: org.h2.Driver
    platform: h2

server:
  port: 8099

logging:
  level:
    org:hibernate:SQL: DEBUG
    custom:tibame201020:coindesk: DEBUG


feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
    connection-timeout: 5000
    socket-timeout: 10000